tokenizer:
  model_name: t5-base
  padding_side: left
  truncation_side: left
  pad_token_as_eos_token: False

reward_fn:
  # id: sacre_bleu
  # id: token_know_f1
  id: bleu_know
  # id: token_ref_f1
  # id: fd_reward
  # id: ours_combined_v2
  # args:
  #   model_path: /p/fewshot/RL4LMs/ckpts/fd_human_comparison.sav
  # id: ours_combined
  # args:
  #   cof_info: 0.05
  #   cof_faith: 0.95

datapool:
  id: faithdial

env:
  n_envs: 2
  args:
    max_prompt_length: 350
    max_episode_length: 50
    terminate_on_eos: True
    context_start_token: 0
    prompt_truncation_side: "right"

alg:
  id: ppo
  args:
    n_steps: 64
    batch_size: 16
    verbose: 1
    learning_rate: 0.0000005
    n_epochs: 5
    ent_coef: 0.00
  kl_div:
    coeff: 0.001
    target_kl: 0.2
  policy:
    id: seq2seq_lm_actor_critic_policy
    args:
      model_name: /p/fewshot/RL4LMs/ckpts/t5-base-fd-supervised/model
      apply_model_parallel: True
      prompt_truncation_side: "right"
      generation_kwargs:
        do_sample: True
        top_k: 0
        temperature: 0.95
        max_new_tokens: 50
    
train_evaluation:
  eval_batch_size: 32
  n_iters: 10000
  eval_every: 100
  save_every: 100
  metrics:
    - id: sacre_bleu
    - id: meteor
    - id: rouge
    - id: bert_know_f1
      args:
        language: en
    - id: knowledge_f1
  generation_kwargs:
    do_sample: True
    top_k: 0
    temperature: 0.95
    max_new_tokens: 50
    