tokenizer:
  model_name: t5-base
  padding_side: left
  truncation_side: left
  pad_token_as_eos_token: False

reward_fn:
  # id: sacre_bleu
  # id: bert_know_f1
  # id: mdd_coherence
  id: ours_combined
  args:
    cof_info: 0.28
    cof_faith: 0.72
    language: en

datapool:
  id: faithdial

env:
  n_envs: 4
  args:
    max_prompt_length: 350
    max_episode_length: 50
    terminate_on_eos: True
    context_start_token: 0
    prompt_truncation_side: "right"

alg:
  id: ppo
  args:
    n_steps: 50
    batch_size: 16
    verbose: 1
    learning_rate: 0.0000005
    n_epochs: 5
  kl_div:
    coeff: 0.001
    target_kl: 0.2
  policy:
    id: seq2seq_lm_actor_critic_policy
    args:
      model_name: ckpts/t5-base-mdd-supervised/model
      apply_model_parallel: True
      prompt_truncation_side: "right"
      generation_kwargs:
        do_sample: True
        top_k: 50
        max_new_tokens: 50
    
train_evaluation:
  eval_batch_size: 32
  n_iters: 20000
  eval_every: 100
  save_every: 100
  metrics:
    - id: sacre_bleu
    - id: meteor
    - id: rouge
    - id: bert_score
      args:
        language: en
    - id: bert_know_f1
      args:
        language: en
    - id: knowledge_f1
    - id: diversity
      args: {}
  generation_kwargs:
    num_beams: 4
    max_new_tokens: 50
    