tokenizer:
  model_name: t5-base
  padding_side: left
  truncation_side: left
  pad_token_as_eos_token: False

reward_fn:
  id: ours_combined
  args: 
    cof_info: 0.45
    cof_faith: 0.45
    language: en
  # id: sacre_bleu
  # id: rouge_l_max
  # args:
  #   max_n: 4
  #   limit_length: True
  #   length_limit: 50
  #   length_limit_type: "words"
  #   apply_avg: True
  #   apply_best: True
  #   alpha: 0.5
  #   weight_factor: 1.2
  #   stemming: True
  # expand: True
  # values:
  #   - id: rouge_l_max
  #     args:
  #       max_n: 4
  #       limit_length: True
  #       length_limit: 100
  #       length_limit_type: "words"
  #       apply_avg: True
  #       apply_best: True
  #       alpha: 0.5
  #       weight_factor: 1.2
  #       stemming: True
  #   - id: rouge_combined

datapool:
  id: multidoc2dial

env:
  n_envs: 2
  args:
    max_prompt_length: 350
    max_episode_length: 50
    terminate_on_eos: True
    context_start_token: 0
    prompt_truncation_side: "right"

alg:
  id: ppo
  args:
    n_steps: 50
    batch_size: 2
    verbose: 1
    learning_rate: 0.0000005
    n_epochs: 5
  kl_div:
    coeff: 0.001
    target_kl: 0.2
  policy:
    id: seq2seq_lm_actor_critic_policy
    args:
      model_name: ckpts/t5-base-mdd-supervised-new/model
      apply_model_parallel: True
      prompt_truncation_side: "right"
      generation_kwargs:
        do_sample: True
        top_k: 50
        max_new_tokens: 50
    
train_evaluation:
  eval_batch_size: 4
  n_iters: 100
  eval_every: 100
  save_every: 100
  metrics:
    - id: sacre_bleu
    - id: meteor
    - id: rouge
    - id: bert_score
      args:
        language: en
    - id: bert_know_f1
      args:
        language: en
    - id: knowledge_f1
    - id: diversity
      args: {}
  generation_kwargs:
    num_beams: 4
    max_new_tokens: 50
    